export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #e6f8f3 0%, #f7fcfa 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #fef9e7 0%, #fffdf4 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #eaf7ff 0%, #f3fbff 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fff2e9 0%, #fff8f4 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #f7f6fe 0%, #fdfdff 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f5f5fc 0%, #fbfbfd 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #f5fff6 0%, #fbfffb 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #e8fef3 0%, #f8fff9 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #f0ecff 0%, #f7f5ff 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fff8f8 100%)" },
];


export const APP_FEATURES = [
      {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no more guesswork.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized and effective.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Interview Simulation Mode",
    description:
      "Practice in a timed, real-world environment. Simulate live interviews and prepare under realistic pressure.",
  }
]