export const CARD_BG = [
  { id: 1, bgcolor: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)" },
  { id: 2, bgcolor: "linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)" },
  { id: 3, bgcolor: "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)" },
  { id: 4, bgcolor: "linear-gradient(135deg, #fef7cd 0%, #fef3c7 100%)" },
  { id: 5, bgcolor: "linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%)" },
  { id: 6, bgcolor: "linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 100%)" },
  { id: 7, bgcolor: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)" },
  { id: 8, bgcolor: "linear-gradient(135deg, #f9fafb 0%, #f3f4f6 100%)" },
  { id: 9, bgcolor: "linear-gradient(135deg, #fefce8 0%, #fef9c3 100%)" },
  { id: 10, bgcolor: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)" },
];


export const APP_FEATURES = [
      {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas — no more guesswork.",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top – making your learning more organized and effective.",
  },
  {
    id: "04",
    title: "Understand the 'Why' Behind Answers",
    description:
      "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.",
  },
  {
    id: "05",
    title: "Interview Simulation Mode",
    description:
      "Practice in a timed, real-world environment. Simulate live interviews and prepare under realistic pressure.",
  }
]